site_name: Kungliga bibliotekets stilguide
docs_dir: './docs'
site_dir: './build'
theme:
    name: null
    custom_dir: 'theme/'
    static_templates:
        - 404.html
    include_search_page: false
    search_index_only: false
    highlightjs: true
    hljs_languages: []
    hljs_style: hybrid
    navigation_depth: 3
    nav_style: primary
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s

plugins:
    - search
    - macros
nav:
    - Introduktion: 'index.md'